### ISSUE TITLE
Cannot unmarshal string into Go struct field

### ISSUE THREAD

**Issue by ktugan** [skord/maxscale_exporter#4]
Unfortunately I didn't have time to pin down the root cause but using maxinfo with the exporter seems to be having issues. Here the error log:

```
json: cannot unmarshal string into Go struct field Server.Port of type int
json: cannot unmarshal string into Go struct field Service.No. Sessions of type float64
json: cannot unmarshal string into Go struct field Status.Value of type float64
json: cannot unmarshal string into Go struct field Event.No. Events Queued of type uint64
```

I added for debugging purposes the results of the endpoint: https://gist.github.com/ktugan/200064a27728a2616af76380100d4863

Here my Dockerfile:
```Dockerfile
# - Builder for the maxinfo exporter -
FROM golang:1.12.4-stretch as maxinfo-exporter

WORKDIR /root
ENV VERSION "v0.1.1"

RUN apt-get install -y git && \
    go get github.com/mariadb-corporation/maxscale_exporter && \
    cd /go/src/github.com/mariadb-corporation/maxscale_exporter && \
    git checkout -b ${VERSION} && \
    go build

# ----- MAXSCALE -------
FROM centos:7

# -- fluentd / td-agent --
	# -- omitted --

# -- node exporter --
	# -- omitted --

# -- maxscale --
ENV MAXSCALE_VERSION=2.3.6
RUN curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash -s -- --mariadb-maxscale-version="${MAXSCALE_VERSION}" && \
    yum -y install maxscale && \
    yum clean all

# -- selfwritten log rotator --
	# -- omitted --

# -- get maxinfo exporter --
COPY --from=maxinfo-exporter /go/src/github.com/mariadb-corporation/maxscale_exporter/maxscale_exporter /root/maxscale_exporter

ADD config.cnf /etc/maxscale.cnf
ADD entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
```

entrypoint.sh omitted heavily
```bash
#!/bin/bash
set -e

/root/maxscale_exporter -address localhost:8002 -port 8082 &

maxscale -d -U root -l stdout
```

ps. I am not sure where this issue really belongs to since in your README you state that this repo is moved to the mariadb-corp which is unfortunately behind this one. Also it does not have issue tracking activated.

**Comment by RubenHoms** [comment]
Good catch, I'm on `v1.4.5` of MaxScale (old I know) and it works perfectly there. Upon inspecting the difference in output from the `maxinfo` JSON endpoint it turns out that the my version outputs integers in some JSON fields while everything is a string for the new version.
So in `v1.4.5` this is the output for `/servers`:
```
{
   "Server":"server1",
   "Address":"mysql",
   "Port":3306,
   "Connections":0,
   "Status":"Master, Running"
}
```
Notice the `Port` here. And based on [your gist](https://gist.github.com/ktugan/200064a27728a2616af76380100d4863) this is it for `v2.3.6`:
```
{
   "Server":"server1",
   "Address":"mysql",
   "Port":"3306",
   "Connections":"0",
   "Status":"Master, Running"
}
```

This could be fixed by adding the `string` option to the structs. This makes it so that it will see the value as a string but converts it to an int/float/whatever you specified as value. This [stackoverflow issue](https://stackoverflow.com/questions/21151765/cannot-unmarshal-string-into-go-value-of-type-int64) deals with the same issue.

To your question about what repo to fix this in, I would say the official repo is the mariadb-corp one, maybe @skord could open it up for issues? Can't do it myself as I have no rights there.

**Comment by skord** [comment]
I no longer work there and won't be maintaining this moving forward. I don't know what employee will be handling this but someone there should be able to address this.

**Comment by ktugan** [comment]
Great catch RubenHoms. I can do a PR but the current setup of the repos is not optimal, it confused me and will also confuse others. I would suggest 

1. removing the fork relationship on the mariadb owner, can be done by contacting the support (https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository). 
2. activating "issues" on the mariadb repo
3. taking the latest commits from this repo and applying it to the fork

@skord would you be able to link somebody with permissions from your old job to do so here? I would love to do so myself but have no permissions.

**Comment by RubenHoms** [comment]
@skord I would be able to maintain this moving forward if you're not. Maybe you could [transfer the repo](https://help.github.com/en/articles/transferring-a-repository) to me so we can disregard the fork on the mariadb repo. The fork of mariadb itself has not had any more activity/commits than this one and the mariadb people can then just work on the exporter through the repo which I can maintain.

@ktugan A PR would be much appreciated, I understand the confusion as it's not ideal in the least at the moment. Once I get the repo transferred you should be able to file an issue there.

**Comment by skord** [comment]
@RubenHoms all yours

**Comment by RubenHoms** [comment]
@skord Awesome, thanks for all the work you put into this.

@ktugan I'll update the references left over in this repo to `skord/maxscale_exporter`. Feel free to shoot a PR on this repo. :+1:

**Comment by ktugan** [comment]
Awesome. I will open up a PR next time I have a bit of time. Would like to test the change before doing so. Thanks for the quick responses all around.
