### ISSUE TITLE
Plans for maxscale 2?

### ISSUE THREAD

**Issue by hoffoo** [skord/maxscale_exporter#5]
Are there plans to support maxscale 2+

Thanks!

**Comment by manucho6** [comment]
maxscale version 2.3.x  is the problem.

**Comment by RubenHoms** [comment]
Yep, I'd love to help out to support version `>2.3.x`. I found out in #4 what the issue is and how we could potentially fix it. I don't have time right now to work on the solution myself but I'm more than willing to help out where needed on a PR.
Closing this because it's a duplicate of #4
