### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by ErwinSteffens** [skord/maxscale_exporter#6]
Hey, I saw this is not maintained anymore and the repo was moved to the official MariaDB corporation repo, but they do not publish an image of it. At least I could not find it. 

Is the image you have published up-to-date? Maybe it is better to tag it. Off-course we could build our own if needed.

**Comment by ErwinSteffens** [comment]
Wrong repo, sorry..

**Comment by RubenHoms** [comment]
Hey @ErwinSteffens, unfortunately this doesn't work for MaxScale > 2.3. (#5 #4). You can go ahead and build the docker image, it should make the latest (master) version. Don't know your usecase but it'd be easier to just grab a binary from the [release page](https://github.com/RubenHoms/maxscale_exporter/releases) and run that.

If you run into problems let me know and we can find out how to fix it together :)

**Comment by ErwinSteffens** [comment]
We are running in in Kubernetes between PHP-FPM and AWS Aurora, so we need to deploy it as a docker image. 

We are running MaxScale v2.3, so as far as I understand this is not going to work yet with this code?

**Comment by RubenHoms** [comment]
Gotcha. Yeah unfortunately it doesn't work with > 2.3 yet, thought it should be very simple to fix. I don't have a setup to test against at the moment and am caught up in other open source work atm. If you would like to look at fixing this check out [this comment](https://github.com/RubenHoms/maxscale_exporter/issues/4#issuecomment-490038393) which kind of sums it up. In my opinion it should only be a few lines to fix this. I would really appreciate any help and would love to help out where possible.

**Comment by RubenHoms** [comment]
Something that just popped into my mind @ktugan has said he would be interested in creating a fix for this, maybe you could work with him on this?

**Comment by ktugan** [comment]
Hey everybody, a colleague and I started to build an alternative to use maxctrl as the exporter instead. I was hoping to test and improve it thoroughly before publishing but couldn't get to it yet. It's not running in production yet.

We are open for any PR or changes and the docker image should be dead simple to build.

Here the code: https://github.com/Vetal1977/maxctrl_exporter

edit: I actually see that we build the docker image already. So its easy to use.

**Comment by ktugan** [comment]
As a clarification. While this exporter will work with 2.3 after fixing the json problem #4, it is still not future proof as the interface for getting the data called maxinfo is deprecated [1].

The exporter linked in my post above fetches the data from the new interface called maxctrl which is supposed to replace maxinfo.

[1] https://mariadb.com/kb/en/mariadb-maxscale-23-mariadb-maxscale-231-release-notes-2018-11-20/
> The maxinfo router has been deprecated and will be removed in a later release.

**Comment by RubenHoms** [comment]
Great work @ktugan, if we could get #4 fixed that would mean there's exporters covering all versions of MaxScale. Would've been awesome to somehow merge your work and my work into one exporter but I can see how that could cause problems. It's awesome to see that you were able to reuse a big part of this codebase to make it compatible with `maxctrl`. Open source :heart: coming your way :smile:

**Comment by ktugan** [comment]
@RubenHoms I would love to fix #4 as promised but life is getting in the way. The fix is easy enough but the testing would take time. You probably understand. I am still determined to do it but the timeline shifted a bit.

Thank you for this great tool! <3

**Comment by RubenHoms** [comment]
@ktugan Not a problem, the great @ErwinSteffens has already fixed this and it's merged and I'm forging a new release right now. I also updated the README to point to your exporter for people using versions > 2.4. Thanks all again for the great work.

**Comment by ErwinSteffens** [comment]
So this issue is closed, but it is actually closing #4. There is still no public docker image available. 

I can help you set it up if needed.

**Comment by RubenHoms** [comment]
Sorry I misunderstood or must've read over this part. I took the `Dockerfile` in the `maxscale_docker` directory, built it and pushed it to docker hub. Does that solve the issue for you?

**Comment by RubenHoms** [comment]
I'm reopening this one because I don't think the Docker image is what we need right now. The one in `maxscale_docker` builds only maxscale and exposes the right ports which is handy while testing. Though we don't have an image for the exporter itself, which is a problem. :laughing: @ErwinSteffens if you have the time could you set this up? I'll gladly integrate it into docker hub with autobuilds and such if that is done.

**Comment by RubenHoms** [comment]
This is fixed by #8, thanks @ErwinSteffens!

**Comment by ErwinSteffens** [comment]
@RubenHoms Thank you!! 

Can you trigger a build for tag `v0.2.1`? I think it is not executed on initial setup, but only when the tag is created.

**Comment by ErwinSteffens** [comment]
@RubenHoms Any chance you can kick off a manual build for tag `v0.2.1`. 

Sorry to send this again, but I have a task to complete and then I can finish it ;-)

**Comment by RubenHoms** [comment]
Sorry for the delay, built for the `v0.2.1` tag and pushed it to docker hub. Also setup a rule to autobuild version tags in docker cloud :ok_hand:

**Comment by ErwinSteffens** [comment]
Awesome, thank you very much!
